// =============================================================================
// PR-4.5A — Re-exporta o template do playbook Motorista para uso no frontend.
// Mantido em src/ para o browser (o mesmo conteúdo existe no shared da edge).
// =============================================================================
import type { PlaybookConfig } from "@/types/legalPlaybook";

export const MOTORISTA_PLAYBOOK_META = {
  name: "Trabalhista — Inicial — Motorista Profissional",
  legal_area: "trabalhista",
  document_type: "peticao_inicial",
  case_subtype: "motorista_profissional",
  description:
    "Playbook padrão para petição inicial trabalhista de motorista profissional (Lei 13.103/2015, jornada, insalubridade, verbas rescisórias, exibição ampliada de documentos).",
} as const;

// Conteúdo idêntico a supabase/functions/_shared/playbooks/seed-motorista.ts
export const MOTORISTA_PLAYBOOK_CONFIG: PlaybookConfig = {
  required_blocks: [
    { key: "dados_funcionais", title: "Dados funcionais", required: true, applicability: "always", keywords: ["dados funcionais", "admissão", "função exercida", "salário"], severity_if_missing: "atencao" },
    { key: "justica_gratuita", title: "Justiça gratuita", required: true, applicability: "always", keywords: ["justiça gratuita", "art. 790", "gratuidade"], severity_if_missing: "atencao", default_text: "Requer os benefícios da justiça gratuita (art. 5º, LXXIV, CF; art. 98 CPC; art. 790, §§3º e 4º, CLT)." },
    { key: "rescisao_indireta", title: "Rescisão indireta (se aplicável)", required: false, applicability: "if_claim_present", keywords: ["rescisão indireta", "art. 483"], severity_if_missing: "atencao" },
    { key: "sucessivo_rescisao_indireta", title: "Pedido sucessivo da rescisão indireta", required: true, applicability: "if_claim_present", keywords: ["pedido sucessivo", "não reconhecimento da rescisão indireta", "hipótese de não reconhecimento"], severity_if_missing: "risco_alto", default_text: "Sucessivamente, na hipótese de não reconhecimento da rescisão indireta, requer o pagamento das verbas rescisórias devidas em razão do rompimento do vínculo por iniciativa do empregador." },
    { key: "jornada_motorista", title: "Jornada do motorista", required: true, applicability: "always", keywords: ["jornada", "controle de jornada", "diário de bordo", "papeleta", "tacógrafo"], severity_if_missing: "atencao" },
    { key: "afastamento_art62", title: "Afastamento do art. 62, I, da CLT", required: true, applicability: "always", keywords: ["art. 62", "meios de controle", "afastamento do art. 62"], severity_if_missing: "atencao" },
    { key: "lei_13103", title: "Lei 13.103/2015", required: true, applicability: "always", keywords: ["lei 13.103", "lei do motorista"], severity_if_missing: "atencao" },
    { key: "horas_extras", title: "Horas extras", required: true, applicability: "if_claim_present", keywords: ["horas extras", "adicional de 50%", "art. 7º, xvi"], severity_if_missing: "atencao" },
    { key: "intrajornada", title: "Intervalo intrajornada", required: true, applicability: "if_claim_present", keywords: ["intrajornada", "art. 71"], severity_if_missing: "atencao" },
    { key: "interjornada", title: "Intervalo interjornada", required: true, applicability: "if_claim_present", keywords: ["interjornada", "art. 66"], severity_if_missing: "atencao" },
    { key: "dsr_domingos_feriados", title: "DSR, domingos e feriados", required: true, applicability: "if_claim_present", keywords: ["dsr", "domingos", "feriados", "lei 605", "súmula 146"], severity_if_missing: "atencao" },
    { key: "remuneracao_variavel", title: "Remuneração variável/produtividade", required: false, applicability: "if_claim_present", keywords: ["produtividade", "comissões", "pagamento por fora", "art. 457"], severity_if_missing: "atencao" },
    { key: "insalubridade", title: "Insalubridade", required: false, applicability: "if_claim_present", keywords: ["insalubridade", "nr-15", "agente químico", "ruído", "vibração", "art. 189", "art. 192"], severity_if_missing: "atencao" },
    { key: "exibicao_documentos", title: "Exibição de documentos (ampliada — motorista)", required: true, applicability: "always", keywords: ["exibição", "art. 400", "súmula 338"], severity_if_missing: "risco_alto", default_text: "Requer a exibição obrigatória de: controles de jornada, diário de bordo, papeletas, ficha de trabalho externo, tacógrafo, relatórios de rastreador/GPS, MDF-e, CT-e, comprovantes de carga e descarga, holerites, TRCT, extratos analíticos de FGTS, fichas de EPI, PGR/PPRA, PCMSO, LTCAT, laudos ambientais e documentos de produtos químicos transportados." },
    { key: "non_limitation_topic", title: "Não limitação dos valores", required: true, applicability: "always", keywords: ["não limitação", "valores estimativos", "art. 840", "meras estimativas", "liquidação de sentença"], severity_if_missing: "risco_alto", placement: "before_requests", default_text: "DA ESTIMATIVA DOS VALORES ATRIBUÍDOS AOS PEDIDOS E DA NÃO LIMITAÇÃO DA CONDENAÇÃO — Os valores atribuídos aos pedidos são meras estimativas para fins do art. 840, §1º, da CLT, não podendo servir de limite à condenação, que deverá ser apurada integralmente em liquidação de sentença." },
    { key: "pedidos_finais", title: "Pedidos finais completos", required: true, applicability: "always", keywords: ["ante o exposto", "requer", "pedidos"], severity_if_missing: "atencao" },
    { key: "pontos_a_confirmar", title: "Pontos a confirmar antes do protocolo", required: false, applicability: "always", keywords: ["pontos a confirmar", "confirmar com o cliente"], severity_if_missing: "sugestao_estrategica" },
  ],
  required_requests: [
    { key: "req_justica_gratuita", title: "Pedido de justiça gratuita", required: true, keywords: ["justiça gratuita"], severity_if_missing: "atencao" },
    { key: "req_rescisao_indireta", title: "Reconhecimento da rescisão indireta", required: false, applicability: "if_claim_present", keywords: ["reconhecimento da rescisão indireta", "art. 483"], severity_if_missing: "atencao" },
    { key: "req_sucessivo", title: "Pedido sucessivo da rescisão indireta", required: true, applicability: "if_claim_present", keywords: ["sucessivamente", "não reconhecimento da rescisão indireta"], severity_if_missing: "risco_alto" },
    { key: "req_saldo_salario", title: "Saldo de salário", required: true, keywords: ["saldo de salário"], severity_if_missing: "atencao" },
    { key: "req_aviso_previo", title: "Aviso-prévio", required: true, keywords: ["aviso-prévio", "aviso previo"], severity_if_missing: "atencao" },
    { key: "req_13_proporcional", title: "13º proporcional", required: true, keywords: ["13º", "décimo terceiro"], severity_if_missing: "atencao" },
    { key: "req_ferias", title: "Férias proporcionais/vencidas + 1/3", required: true, keywords: ["férias", "1/3"], severity_if_missing: "atencao" },
    { key: "req_fgts", title: "FGTS", required: true, keywords: ["fgts"], severity_if_missing: "atencao" },
    { key: "req_multa_40", title: "Multa de 40% do FGTS", required: true, keywords: ["multa de 40", "40% do fgts"], severity_if_missing: "atencao" },
    { key: "req_multa_477", title: "Multa do art. 477", required: true, keywords: ["art. 477", "multa do art. 477"], severity_if_missing: "atencao" },
    { key: "req_multa_467", title: "Multa do art. 467", required: true, keywords: ["art. 467", "multa do art. 467"], severity_if_missing: "atencao" },
    { key: "req_horas_extras", title: "Horas extras + reflexos", required: true, keywords: ["horas extras"], severity_if_missing: "atencao" },
    { key: "req_intrajornada", title: "Intrajornada", required: true, keywords: ["intrajornada"], severity_if_missing: "atencao" },
    { key: "req_interjornada", title: "Interjornada", required: true, keywords: ["interjornada"], severity_if_missing: "atencao" },
    { key: "req_dsr", title: "Domingos/feriados", required: true, keywords: ["domingos", "feriados"], severity_if_missing: "atencao" },
    { key: "req_integracao_variavel", title: "Integração da remuneração variável", required: false, applicability: "if_claim_present", keywords: ["integração", "pagamento por fora", "comissões"], severity_if_missing: "atencao" },
    { key: "req_insalubridade", title: "Adicional de insalubridade", required: false, applicability: "if_claim_present", keywords: ["insalubridade"], severity_if_missing: "atencao" },
    { key: "req_exibicao", title: "Exibição de documentos", required: true, keywords: ["exibição de documentos", "art. 400"], severity_if_missing: "risco_alto" },
    { key: "req_nao_limitacao", title: "Não limitação da condenação", required: true, keywords: ["não limitando a condenação", "não limitação", "não seja limitad"], severity_if_missing: "risco_alto", default_text: "Requer a condenação integral da Reclamada, NÃO LIMITANDO A CONDENAÇÃO aos valores meramente estimativos indicados nesta inicial, que deverão ser apurados INTEGRALMENTE em liquidação de sentença (art. 840, §1º, CLT)." },
    { key: "req_honorarios", title: "Honorários sucumbenciais", required: true, keywords: ["honorários", "art. 791-a"], severity_if_missing: "atencao" },
    { key: "req_juros_correcao", title: "Juros e correção monetária", required: true, keywords: ["juros", "correção monetária"], severity_if_missing: "atencao" },
    { key: "req_abatimento", title: "Abatimento de valores pagos sob mesmo título", required: true, keywords: ["abatimento", "mesmo título"], severity_if_missing: "atencao" },
    { key: "req_provas", title: "Produção de provas", required: true, keywords: ["produção de provas", "protesta"], severity_if_missing: "atencao" },
    { key: "req_valor_causa", title: "Valor da causa", required: true, keywords: ["valor da causa", "dá-se à causa"], severity_if_missing: "atencao" },
  ],
  document_requests: [
    { key: "ctps", label: "CTPS", importance: "obrigatorio", keywords: ["ctps", "carteira de trabalho"] },
    { key: "holerites", label: "Holerites/contracheques", importance: "obrigatorio", keywords: ["holerites", "contracheques", "recibos de pagamento"] },
    { key: "fgts_extrato", label: "Extrato analítico de FGTS", importance: "obrigatorio", keywords: ["extrato analítico", "extrato do fgts"] },
    { key: "trct", label: "TRCT", importance: "se_aplicavel", keywords: ["trct"] },
    { key: "pedido_demissao", label: "Pedido de demissão", importance: "se_aplicavel", keywords: ["pedido de demissão"] },
    { key: "controles_jornada", label: "Controles de jornada", importance: "obrigatorio", keywords: ["controles de jornada", "cartões de ponto"] },
    { key: "diario_bordo", label: "Diário de bordo", importance: "obrigatorio", keywords: ["diário de bordo", "diario de bordo"] },
    { key: "papeletas", label: "Papeletas", importance: "obrigatorio", keywords: ["papeleta"] },
    { key: "ficha_trabalho_externo", label: "Ficha de trabalho externo", importance: "obrigatorio", keywords: ["ficha de trabalho externo"] },
    { key: "tacografo", label: "Tacógrafo", importance: "obrigatorio", keywords: ["tacógrafo", "tacografo"] },
    { key: "gps", label: "Relatórios de rastreador/GPS", importance: "obrigatorio", keywords: ["rastreador", "gps"] },
    { key: "relatorios_jornada", label: "Relatórios de jornada", importance: "recomendado", keywords: ["relatórios de jornada"] },
    { key: "relatorios_viagem", label: "Relatórios de viagem", importance: "recomendado", keywords: ["relatórios de viagem"] },
    { key: "cte", label: "CT-e", importance: "obrigatorio", keywords: ["ct-e", "cte", "conhecimento de transporte"] },
    { key: "mdfe", label: "MDF-e", importance: "obrigatorio", keywords: ["mdf-e", "mdfe", "manifesto de documentos"] },
    { key: "carga_descarga", label: "Comprovantes de carga e descarga", importance: "recomendado", keywords: ["carga e descarga", "romaneio"] },
    { key: "rotas", label: "Documentos de rotas", importance: "recomendado", keywords: ["rotas"] },
    { key: "km", label: "Relatórios de quilometragem", importance: "recomendado", keywords: ["quilometragem", "km rodado"] },
    { key: "produtividade", label: "Relatórios de produtividade", importance: "recomendado", keywords: ["produtividade"] },
    { key: "produtividade_pgto", label: "Comprovantes de pagamento de produtividade/bônus", importance: "recomendado", keywords: ["bônus", "produtividade"] },
    { key: "recibos_ferias", label: "Recibos de férias", importance: "recomendado", keywords: ["recibos de férias"] },
    { key: "ferias_pgto", label: "Comprovantes de pagamento de férias", importance: "recomendado", keywords: ["pagamento de férias"] },
    { key: "epi_fichas", label: "Fichas de EPI", importance: "obrigatorio", keywords: ["fichas de epi", "epi"] },
    { key: "epi_certificados", label: "Certificados de treinamento de EPI", importance: "recomendado", keywords: ["treinamento de epi"] },
    { key: "pgr", label: "PGR/PPRA", importance: "obrigatorio", keywords: ["pgr", "ppra"] },
    { key: "pcmso", label: "PCMSO", importance: "obrigatorio", keywords: ["pcmso"] },
    { key: "ltcat", label: "LTCAT", importance: "obrigatorio", keywords: ["ltcat"] },
    { key: "laudos_ambientais", label: "Laudos ambientais", importance: "obrigatorio", keywords: ["laudos ambientais", "laudo ambiental"] },
    { key: "quimicos_fichas", label: "Fichas/documentos de produtos químicos", importance: "recomendado", keywords: ["fispq", "produtos químicos", "mopp"] },
    { key: "quimicos_seguranca", label: "Documentos de segurança dos produtos químicos", importance: "recomendado", keywords: ["antt", "segurança dos produtos"] },
  ],
  sensitive_theses: [
    { key: "sumula_450_adpf_501", label: "Súmula 450/TST e ADPF 501/STF", warning: "Não redigir como tese segura sem revisão humana.", required_marker: "[REVISAR ADPF 501/STF E ENTENDIMENTO ATUAL]", keywords: ["súmula 450", "adpf 501", "férias pagas em atraso"], severity: "risco_alto" },
    { key: "adi_5766", label: "ADI 5.766/STF (sucumbência do beneficiário da gratuidade)", warning: "Entendimento pode oscilar — revisar antes de protocolar.", required_marker: "[REVISAR ENTENDIMENTO ATUAL SOBRE ADI 5.766/STF]", keywords: ["adi 5.766", "adi 5766"], severity: "risco_alto" },
    { key: "intrajornada_pos_reforma", label: "Intervalo intrajornada pós-Reforma", warning: "Após 11/11/2017 pagar apenas o tempo suprimido, natureza indenizatória.", required_marker: "[REVISAR APLICAÇÃO TEMPORAL — art. 71, §4º, CLT pós-Reforma]", keywords: ["art. 71, §4º", "art. 71 §4"], severity: "risco_alto" },
    { key: "base_insalubridade", label: "Base de cálculo da insalubridade", warning: "SV 4/STF — revisar entendimento atual do TST.", required_marker: "[REVISAR ENTENDIMENTO ATUAL — SV 4/STF]", keywords: ["base de cálculo da insalubridade", "sv 4", "súmula vinculante 4"], severity: "atencao" },
    { key: "art_62_motorista", label: "Art. 62, I, da CLT para motorista", warning: "Havendo meios de controle, afastar expressamente.", required_marker: "[REVISAR FUNDAMENTO — afastamento do art. 62, I, CLT]", keywords: ["art. 62, i"], severity: "atencao" },
    { key: "rescisao_fgts", label: "Rescisão indireta por FGTS irregular", warning: "Tese sensível — revisar jurisprudência atual.", required_marker: "[REVISAR JURISPRUDÊNCIA ATUALIZADA — rescisão indireta por FGTS]", keywords: ["rescisão indireta", "fgts irregular"], severity: "atencao" },
    { key: "remuneracao_variavel_sens", label: "Remuneração variável/produtividade", warning: "Confirmar habitualidade e forma de pagamento antes de sustentar integração.", required_marker: "[CONFIRMAR COM O CLIENTE]", keywords: ["pagamento por fora", "produtividade paga por fora"], severity: "atencao" },
  ],
  review_checklist: [
    { key: "chk_sucessivo", label: "Há pedido sucessivo se a rescisão indireta não for reconhecida?", required: true, severity: "risco_alto" },
    { key: "chk_nao_limitacao", label: "Há pedido de não limitação da condenação?", required: true, severity: "risco_alto" },
    { key: "chk_docs_motorista", label: "CT-e, MDF-e, tacógrafo e GPS estão no pedido de exibição?", required: true, severity: "risco_alto" },
    { key: "chk_calc_pendentes", label: "Todos os pedidos monetários sem valor seguro estão com [CALCULAR VALOR — revisar memória de cálculo]?", required: true, severity: "atencao" },
    { key: "chk_intrajornada_reforma", label: "Se contrato atravessa a Reforma, intrajornada foi segmentada?", required: true, severity: "risco_alto" },
    { key: "chk_pericia", label: "Insalubridade tem pedido de perícia (art. 195 CLT)?", required: false, severity: "atencao" },
  ],
  drafting_instructions: [
    "Não inventar jurisprudência.",
    "Manter cálculos inseguros como [CALCULAR VALOR — revisar memória de cálculo].",
    "Nunca copiar fatos, nomes, CPFs ou valores do modelo do escritório.",
    "Redigir o tópico obrigatório de não limitação IMEDIATAMENTE antes do pedido final.",
    "Marcar teses sensíveis com o marcador exato indicado.",
  ],
};
